---
site:
  title: OpenShift Dev Day
  url: https://github.com/rhpds/ocp-dev-days-rdshw-showroom
  start_page: modules:en:index.adoc

content:
  sources:
    - url: .
      start_path: content/en
      branches: HEAD
    - url: .
      start_path: content/ja
      branches: HEAD

ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/latest/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

antora:
  extensions:
    - require: '@sntke/antora-mermaid-extension'
      mermaid_library_url: https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs
      script_stem: header-scripts
      mermaid_initialize_options:
        start_on_load: true
    # - require: '@andrew-jones/antora-tabs-extension'

output:
  dir: ./www
